service: general-lambda-functions

frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: us-west-2
  timeout: 600
  environment:
    STAGE: ${opt:stage, 'dev'}
    BACKENDLESS_APP_KEY_PROD: ${env:BACKENDLESS_APP_KEY_PROD}
    BACKENDLESS_APP_ID_PROD: ${env:BACKENDLESS_APP_ID_PROD}
    BACKENDLESS_REST_KEY_PROD: ${env:BACKENDLESS_REST_KEY_PROD}
    AIRTABLE_API_KEY: ${env:AIRTABLE_API_KEY}
  tracing:
    apiGateway: true
    lambda: true

functions:
  isgOrderSourceToASCMLogistics:
    handler: src/airtable.isgOrderSourceToASCMLogistics
    events:
      - http:
          path: /airtable/ascm-logistics
          method: GET
          cors: true

  getInventoryByUserID:
    handler: src/inventory.getInventoryByUserIDLambdaFunc
    events:
      - http:
          path: /inventory
          method: POST
          cors: true

  sendOutSKUOutbounds:
    handler: src/sku_outbounds.sendOut
    events:
      - http:
          path: /sku_outbounds/{sku_outbound_id}/send_out
          method: POST
          cors: true

  sendOutSKUOutboundISGOrders:
    handler: src/sku_outboundisgorders.sendOut
    events:
      - http:
          path: /sku_outbound_isgorders/{sku_outbound_isgorder_id}/send_out
          method: POST
          cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    noPrependStageInUrl: true
