begin;

create table if not exists pttb_outbounds_shopeeorders
(
    id uuid not null primary key default uuid_generate_v4(),
    created timestamp with time zone default current_timestamp not null,
    updated timestamp with time zone,
    owner_id text,
    airtable_record_id text,
    ascm_sku text,
    bundle_deal_indicator text,
    buyer_paid_shipping_fee float,
    cancel_reason text,
    city text,
    commision_fee_incl_gst float,
    country text,
    credit_card_discount_total float,
    deal_price float,
    delivery_address text,
    district text,
    estimated_ship_out_date text,
    estimated_shipping_fee float,
    final_ascm_sku text,
    get_ascm_sku text,
    logistics_status text,
    no_of_product_in_order int,
    note text,
    order_complete_time text,
    order_creation_date text,
    order_id text,
    order_paid_time text,
    order_status text,
    order_total_weight float,
    original_price float,
    parent_sku_reference_no text,
    phone_number text,
    product_name text,
    product_subtotal text,
    province text,
    quantity int,
    receiver_name text,
    remark_from_buyer text,
    remarks_1 text,
    return_refund_status text,
    reverse_shipping_fee float,
    seller_absorbed_coin_cashback float,
    seller_bundle_discount float,
    seller_discount float,
    seller_rebate float,
    seller_voucher float,
    server_fee_incl_gst float,
    ship_time text,
    shipment_method text,
    shipping_option text,
    shipping_rebate_estimate float,
    shopee_bundle_discount float,
    shopee_coins_offset float,
    shopee_rebate float,
    shopee_voucher float,
    sku_full_name text,
    sku_reference_no text,
    sku_total_weight float,
    store_name text,
    total_amount float,
    town text,
    tracking_number text,
    transaction_fee_incl_gst float,
    username_buyer text,
    variation_name text,
    voucher_code text,
    zip_code text,
    -- relational fields
    sku_matching_id uuid
);

commit;
