begin;

create table if not exists pttb_outbounds_shopifyorders
(
    id uuid not null primary key default uuid_generate_v4(),
    created timestamp with time zone default current_timestamp not null,
    updated timestamp with time zone,
    owner_id text,
    airtable_record_id text,
    ascm_id text,
    ascm_uftracking text,
    cancelled_at timestamp with time zone,
    created_at timestamp with time zone,
    created_time timestamp with time zone,
    discount_amount text,
    discount_code text,
    email text,
    email_text_repeat text,
    final_ascm_ids text,
    final_uf_tracking text,
    financial_status text,
    fulfillment_status text,
    internal_order_number int,
    latest_uf_status text,
    line_item_name text,
    line_item_price float,
    line_item_quantity int,
    line_item_sku text,
    link_ascm_skus text,
    link_auto_uf_submit text,
    link_auto_uf_submit_ascm text,
    mobile_repeat text,
    name text,
    note_attributes text,
    notes text,
    payment_method text,
    shipping_address1 text,
    shipping_address2 text,
    shipping_company text,
    shipping_country text,
    shipping_method text,
    shipping_name text,
    shipping_phone text,
    shipping_repeat text,
    shipping_street text,
    shipping_zip text,
    status text,
    store_name text,
    tags text,
    test_date_field timestamp with time zone,
    to_ship_courier text,
    total float,
    uf_tracking text,
    -- relational fields
    sku_matching_id uuid
);

commit;
